name: .NET Continuous Deployment

on:
  push:
    branches: [ master ]
    paths: 
      - src/DiscosExtractor/**
  workflow_dispatch:
jobs:

  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run tests
      run: dotnet test --logger GitHubActions ./src/DiscosExtractor.sln

  semantic-release:
    needs: test
    name: Determine New Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_version.outputs.new_version }}
      tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
    - uses: actions/checkout@v3 # Need the full commit history for conventional commit
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
  windows-build:
    needs: semantic-release
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v3
      - name: Build Self-Contained
        run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:UseAppHost=true -p:PackageVersion=${{ needs.semantic-release.outputs.version }} --self-contained ./src/DiscosExtractor.sln -o ./bin/Release/win-x64
      - uses: actions/upload-artifact@v3
        with:
          name: win-exe
          path: ./bin/Release/win-x64/discosextractor.exe
          
  linux-build:
    needs: semantic-release
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v3
      - name: Build Self-Contained
        run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:UseAppHost=true -p:PackageVersion=${{ needs.semantic-release.outputs.version }} --self-contained ./src/DiscosExtractor.sln -o ./bin/Release/linux-x64
      - uses: actions/upload-artifact@v3
        with:
          name: linux-exe
          path: ./bin/Release/linux-x64/discosextractor
      
  mac-build:
    needs: semantic-release
    name: Build for MacOS
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v3
      - name: Build Self-Contained
        run: dotnet publish -c Release -r osx-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PackageVersion=${{ needs.semantic-release.outputs.version }} -p:UseAppHost=true --self-contained ./src/DiscosExtractor.sln -o ./bin/Release/osx-x64 
      - uses: actions/upload-artifact@v3
        with:
            name: mac-exe
            path: ./bin/Release/osx-x64/discosextractor
      
  release:
    needs:
      - windows-build
      - linux-build
      - mac-build
      - semantic-release # Need this to share context
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: win-exe
          path: ./binaries/windows
      - uses: actions/download-artifact@v3
        with:
          name: linux-exe
          path: ./binaries/linux
      - uses: actions/download-artifact@v3
        with:
          name: mac-exe
          path: ./binaries/osx
      - name: Create tarball
        run: tar -czf binaries.tar.gz binaries
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.semantic-release.outputs.tag }}
          name: Release ${{ needs.semantic-release.outputs.version }}
          body: ${{ needs.semantic-release.outputs.changelog }}
          artifacts: ./binaries.tar.gz
